version: '3.8'

services:
  redis_db:
    extends:
      file: ./services/docker-compose-redis.yml
      service: redis_db

  db:
    extends:
      file: ./services/docker-compose-db.yml
      service: db

  backend:
    depends_on:
      - db
      - redis_db
    image: blockscout/blockscout:${DOCKER_TAG:-master}
    pull_policy: always
    restart: always
    stop_grace_period: 5m
    container_name: 'backend'
    links:
      - db:database
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout.env
    environment:
      ETHEREUM_JSONRPC_VARIANT: 'geth'
      ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:18545/
      ETHEREUM_JSONRPC_TRACE_URL: http://host.docker.internal:18545/
      ETHEREUM_JSONRPC_WS_URL: ws://host.docker.internal:18546/
      INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: 'false'
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 'false'
      INDEXER_MEMORY_LIMIT: '2Gb'
      INDEXER_CATCHUP_BLOCKS_BATCH_SIZE: '5'
      INDEXER_CATCHUP_BLOCKS_CONCURRENCY: '2'
      DATABASE_URL: postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
      CHAIN_ID: '8131'
      MICROSERVICE_VISUALIZE_SOL2UML_URL: 'http://host.docker.internal:8152/'
      MICROSERVICE_SIG_PROVIDER_URL: 'http://host.docker.internal:8151/'
    ports:
      - 4000:4000
    volumes:
      - ./logs/:/app/logs/

  visualizer:
    extends:
      file: ./services/docker-compose-visualizer.yml
      service: visualizer

  sig-provider:
    extends:
      file: ./services/docker-compose-sig-provider.yml
      service: sig-provider

  stats-db:
    depends_on:
      - backend
    extends:
      file: ./services/docker-compose-stats.yml
      service: stats-db

  stats:
    depends_on:
      - stats-db
    extends:
      file: ./services/docker-compose-stats.yml
      service: stats
